version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - yarn install --ignore-engines
  build:
    commands:
      - yarn build

artifacts:
  base-directory: build
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'
